#!/bin/bash

#Variables
FLAG=$1
OPTION=$2
NAME=$3
IP=$4
ZONE=$5

echo "Gekozen option is $OPTION, and zone $ZONE"

while getopts 't:' OPTIONS; do
	case "$OPTIONS" in
		t)
		   if [ $OPTION == A ]
			then
				echo "Writing record"
				echo ";Name Server Records"		 >>/etc/bind/db.$ZONE
				echo "${NAME}	IN	A	${IP}"    >>/etc/bind/db.$ZONE
                   
		   elif [ $OPTION == MX ]
			then
				echo "Creating record"
				echo ";Name Server Records"		 >>/etc/bind/db.$ZONE
				echo "${NAME}   IN      A       ${IP}"    >>/etc/bind/db.$ZONE
				echo "Writing mx record"
				echo ";Name Server MX"			>>/etc/bind/db.$ZONE
				echo "@	IN	MX	10 ${NAME}.${ZONE}."  >>/etc/bind/db.$ZONE

		   elif [ $OPTION == CNAME ]
			then
				echo "Creating CNAME record"
				echo ";Name Server CNAME"		>>/etc/bind/db.$ZONE
				echo "${NAME}   IN      CNAME       ${IP}"    >>/etc/bind/db.$ZONE
		  else
				echo "$OPTION"
		  fi
	esac
done

#Increment
last=$(grep "Serial" /etc/bind/db.$ZONE | tr -dc '0-9')
new=$((last + 1))
sed -i "s/.*Serial.*/\t\t        $new    ;Serial/g" /etc/bind/db.$ZONE

rndc reload
systemctl restart bind9
