#!/bin/bash

#Variables
FLAG=$1
OPTION=$2
NAME=$3
IP=$4
ZONE=$5

echo "Gekozen option is $OPTION"

while getopts 't:' OPTIONS; do
	case "$OPTIONS" in
		t)
		   if [ $OPTION == A ]
			then
				echo "Writing record"
				echo ";Name Server Records"		 >>/etc/bind/db.$ZONE
				echo "${RNAME}	IN	A	${IP}"    >>/etc/bind/db.$ZONE
                   elif [ $RTYPE == MX ]
			then
				echo "Creating record"
				echo ";Name Server Records"		 >>/etc/bind/db.$ZONE
				echo "${RNAME}   IN      A       ${IP}"    >>/etc/bind/db.$ZONE
				echo "Writing mx record"
				echo ";Name Server MX"			>>/etc/bind/db.$ZONE
				echo "@	IN	MX	10 ${RNAME}.${ZONE}."  >>/etc/bind/db.$ZONE
		   elif [ $RTYPE == CNAME ]
			then
				echo "Creating CNAME record"
				echo ";Name Server CNAME"		>>/etc/bind/db.$ZONE
				echo "${RNAME}   IN      CNAME       ${IP}"    >>/etc/bind/db.$ZONE
		  else
				echo "$RTYPE"
		  fi
	esac
done

rndc reload
systemctl restart bind9
