#!/bin/bash
#User is root check
if [ "$EUID" -ne 0 ];then
    echo "Please run this script as root user"
    exit 1
fi

NAME=$(echo "$1" | cut -d '.' -f 1)
SUBDOMAIN=$(echo "$1" | cut -d "." -f2)
echo "$NAME"

if [ ! -f "/etc/bind/db.$SUBDOMAIN.thomas-pede.sb.uclllabs.be" ]; then
    echo "subdomain $SUBDOMAIN does not exist"
    exit 1
fi

cat >> /etc/apache2/sites-available/$NAME.conf << EOL
	<VirtualHost *:80>
		ServerName $1
		ServerAlias $1
		DocumentRoot /var/www/html/$NAME
		LogLevel info
		ErrorLog ${APACHE_LOG_DIR}/$NAME-error.log
		CustomLog ${APACHE_LOG_DIR}/$NAME-acces.log combined
	</VirtualHost>
EOL

mkdir /var/www/html/$NAME
echo "welcome vhost_name" >> /var/www/html/$NAME/index.html
echo "welcome www.$(echo "$1" | cut -d '.' -f 1-2)" >> /var/www/html/$NAME/index.html

a2ensite $NAME
systemctl reload apache2

